---
- hosts: localhost
  connection: local
    
  tasks:     
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item }}"
        port: 22
        delay: 50
        timeout: 320
        sleep: 50
        state: started
      with_inventory_hostnames:
        - all

    - name: whoami
      command: whoami 

    - name: ECHO USER
      command: "echo ${DOCKER_USER}"