---
- hosts: localhost
  connection: local
    
  tasks:     
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item }}"
        port: 22
        delay: 30
        timeout: 320
        sleep: 30
        state: started
      with_inventory_hostnames:
        - all