---
- hosts: localhost
  connection: local
    
  tasks:     
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item }}"
        port: 22
        delay: 30
        timeout: 320
        sleep: 30
        state: started
      with_inventory_hostnames:
        - all
    
#optional possible option
#    - name: optional install python on build&stage instances
#      command: "ssh -o 'StrictHostKeyChecking=no' ubuntu@{{ item }} -i ./key4CW.pem 'sudo apt update ; sudo apt install -y python ;'"
#      with_inventory_hostnames:
#        - all

- name: Build stage
  hosts: build
  remote_user: ubuntu
  become: yes
  become_user: root
      
  vars:
    ansible_ssh_private_key_file: "./key4CW.pem"
    
  tasks:
    - name: update apt cache
      apt: update_cache=true
    
    - name: Install packages
      apt: pkg={{ item }} state=latest
      with_items:
        - default-jdk
        - maven
        - git
        - docker.io
    
    - name: clone boxfuse
      git: repo=https://github.com/boxfuse/boxfuse-sample-java-war-hello.git dest=/tmp/boxfuse
      tags: deploy
       
    - name: package boxfuse war
      command: mvn package -f /tmp/boxfuse

# 4test only copy war file to jenkins host
#    - name: Copy WAR
#      fetch:
#        src: /tmp/boxfuse/target/hello-1.0.war
#        dest: ./hello-1.0.war
#        flat: true
    
    - name: Copy dockerfile to build instance
      copy:
        src: ./Dockerfile
        dest: /tmp/boxfuse/target
    
    - name: Build docker image
      command: docker build -f /tmp/boxfuse/target/Dockerfile -t webapp /tmp/boxfuse

    - name: Tag docker image
      command: docker tag webapp:latest zi10ge/appcw:latest

    - debug:
        msg: test {{ DOCKER_USER }}
  
    - debug:
        msg: test $DOCKER_USER 
      
    - name: Login on dockerhub
      command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

    - name: Push dockerimage to github
      command: docker push zi10ge/appcw:latest

# for this alternative need python >= 2.7 
#    - name: Build and push docker image to github
#      docker_image:
#        build:
#          path: /tmp/boxfuse
#        name: zi10ge/appcw
#        push: yes
#        tag: latest
#        source: build