---
- hosts: localhost
  connection: local
    
  tasks:     
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item }}"
        port: 22
        delay: 30
        timeout: 320
        sleep: 30
        state: started
      with_inventory_hostnames:
        - all
    
#optional possible option
#    - name: optional install python on build&stage instances
#      command: "ssh -o 'StrictHostKeyChecking=no' ubuntu@{{ item }} -i ./key4CW.pem 'sudo apt update ; sudo apt install -y python ;'"
#      with_inventory_hostnames:
#        - all

- name: Build stage
  hosts: build
  remote_user: ubuntu
  become: yes
  become_user: root
      
  vars:
    ansible_ssh_private_key_file: "./key4CW.pem"
    
  tasks:
    - name: Test message
      command: echo "HI ALL!"
