---
- hosts: localhost
  connection: local
    
  tasks:     
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item }}"
        port: 22
        delay: 5
        timeout: 320
        sleep: 10
        state: started
      with_inventory_hostnames:
        - all
    
- name: Build stage
  hosts: build
  remote_user: ubuntu
  become: yes
  become_user: root
      
  vars:
    ansible_ssh_private_key_file: "./key4CW.pem"
    
  tasks:
    - name: Test message
      command: echo "HI ALL!"
    