---
- name: Build instance
  hosts: build
  remote_user: ubuntu
  become: yes
  become_user: root
      
  vars:
    ansible_ssh_private_key_file: "./key4CW.pem"
    
  tasks:
    
    - name: Install build tools
      apt: pkg={{ item }} state=latest
      with_items:
        - default-jdk
        - maven
        - git
        - docker.io
    
    - name: clone boxfuse
      git: repo=https://github.com/boxfuse/boxfuse-sample-java-war-hello.git dest=/tmp/boxfuse
      tags: deploy
       
    - name: Package boxfuse war
      command: mvn package -f /tmp/boxfuse

    - name: Add ubuntu to docker group
      command: sudo usermod -aG docker ubuntu

    - name: Copy dockerfile to build instance
      copy:
        src: ./Dockerfile
        dest: /tmp/boxfuse/target
    
    - name: Build docker image
      command: docker build -f /tmp/boxfuse/target/Dockerfile -t webapp /tmp/boxfuse

    - name: Tag docker image
      command: docker tag webapp:latest zi10ge/appcw:latest
     
    - name: Login on dockerhub
      command: 'docker login -u {{ foo2 }} -p {{ foo1 }}'

    - name: Push dockerimage to github
      command: 'docker push zi10ge/appcw:latest'