---
- name: Stage instance
  hosts: stage
  remote_user: ubuntu
  become: yes
  become_user: root
      
  vars:
    ansible_ssh_private_key_file: "./key4CW.pem"
    
  tasks:
    
    - name: Install docker
      apt: pkg={{ item }} state=latest
      with_items:
        - docker.io
    
    - name: Run docker image
      command: docker run -d -p 8080:8080 zi10ge/appcw:latest